

title: "lian的技术学习笔记 | 新手成长记录"
email: liu704838@163.com
description: >-
 现代的我们需要的不再是文学，而是文案。

author:
  name: "lian"
  avatar: "/assets/images/avatar.jpg"
  bio: "坚持就是胜利"

baseurl: ""
url: "https://lianshu18.github.io"
theme: minima

social_links:
  github: https://github.com/lianshu18

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  # 添加到 _config.yml 末尾
include:
  - assets/images